version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3
jobs:
  build:
    working_directory: ~/pluto-demo
    docker:
      - image: julia:1.5.3
    steps:
      - checkout
      - run:
          name: Test and get code coverage for WignerTools
          command: julia -e 'using Pkg; Pkg.develop(path="WignerTools"); Pkg.test("WignerTools", coverage=true)'
      - run:
          name: Process code coverage
          command: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; coverage = process_folder("WignerTools/src"); LCOV.writefile("coverage-lcov.info", coverage)'
      - codecov/upload:
          file: "coverage-lcov.info"
          token: "dcacaacc-a3d7-46e8-921d-5aa835c6d305"
