version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3
jobs:
  build:
    working_directory: ~/pluto-demo
    docker:
      - image: julia:1.5.3
    steps:
      - checkout
      - run:
          name: Test and get code coverage for WignerTools
          command: julia --project --code-coverage=coverage-lcov.info -e 'using Pkg; Pkg.test("WignerTools")'
      - codecov/upload:
          file: "coverage-lcov.info"
          token: "dcacaacc-a3d7-46e8-921d-5aa835c6d305"
